// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import Navbar from "./Component/Navbar";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body  data-theme="dark"
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         <Navbar></Navbar>
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }

// "use client";
// import { ThemeProvider } from "@/context/ThemeContext";
// import { AuthProvider } from "@/context/AuthContext";
// import "./globals.css";
// import { Geist, Geist_Mono } from "next/font/google";
// import Navbar from "./Component/Navbar";
// import NextAuthProvider from "@/provider/NextAuthProvider";

// const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export default function RootLayout({ children }) {
//   return (
//     <NextAuthProvider>
//       <html lang="en" suppressHydrationWarning>
//         <head>
//           <script
//             dangerouslySetInnerHTML={{
//               __html: `
//               (function() {
//                 try {
//                   const theme = localStorage.getItem('theme') || 'light';
//                   document.documentElement.setAttribute('data-theme', theme);
//                 } catch (e) {}
//               })();
//             `,
//             }}
//           />
//         </head>
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           {/* AuthProvider wraps ThemeProvider */}
//           <AuthProvider>
//             <ThemeProvider>
//               <Navbar /> {/* Navbar uses context now */}
//               <main className="pt-16 border">{children}</main>
//             </ThemeProvider>
//           </AuthProvider>
//         </body>
//       </html>
//     </NextAuthProvider>
//   );
// }



"use client";
import { ThemeProvider } from "@/context/ThemeContext";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Component/Navbar";
import NextAuthProvider from "@/provider/NextAuthProvider";
import GlobalLoader from "./Component/GlobalLoader";


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <script
            dangerouslySetInnerHTML={{
              __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme') || 'light';
                  document.documentElement.setAttribute('data-theme', theme);
                } catch (e) {}
              })();
            `,
            }}
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthProvider>
            <ThemeProvider>
              {/* ২. গ্লোবাল লোডার এখানে থাকবে */}
              <GlobalLoader /> 
              
              <Navbar />
              <main className="pt-16 border">{children}</main>
            </ThemeProvider>
          </AuthProvider>
        </body>
      </html>
    </NextAuthProvider>
  );
}